app:
  image: vprocontainers/vprofileapp
  tag: latest
  replicas: 1
  containerPort: 8080
  servicePort: 8080
  defaultUser: guest

db:
  image: vprocontainers/vprofiledb
  tag: latest
  replicas: 1
  containerPort: 3306
  servicePort: 3306
  storageClass: gp2
  storageSize: 3Gi
  defaultUser: root

memcached:
  image: memcached
  tag: latest
  replicas: 1
  containerPort: 11211
  servicePort: 11211
  defaultUser: cache

rabbitmq:
  image: rabbitmq
  tag: latest
  replicas: 1
  containerPort: 5672
  servicePort: 5672
  defaultUser: guest

initcontainers:
  image: busybox
  tag: latest

ingress:
  enabled: true
  host: http://k8s-default-vprofile-8288e4772a-1362856882.us-east-1.elb.amazonaws.com 
  servicePort: 8080

secrets:
  dbPassword: vprodbpass
  rmqPassword: guest

dockerregistry:
  enabled: false
  server: https://index.docker.io/v1/
  username: ""
  password: ""
  email: ""
