apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  type: ClusterIP
  selector:
    app: vproapp
  ports:
  - name: http
    port: {{ .Values.app.servicePort }}
    targetPort: {{ .Values.app.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  type: ClusterIP
  selector:
    app: vpromc
  ports:
  - name: memcached
    port: {{ .Values.memcached.servicePort }}
    targetPort: {{ .Values.memcached.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  type: ClusterIP
  selector:
    app: vpromq01
  ports:
  - name: rabbitmq
    port: {{ .Values.rabbitmq.servicePort }}
    targetPort: {{ .Values.rabbitmq.containerPort }}
