apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: http://k8s-default-vprofile-8288e4772a-1362856882.us-east-1.elb.amazonaws.com/
    http: http://k8s-default-vprofile-8288e4772a-1362856882.us-east-1.elb.amazonaws.com/
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vproapp-service
            port:
              number: 8080
